# Generated by Django 2.1.3 on 2018-11-22 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanno', models.CharField(max_length=6, unique=True)),
                ('loantype', models.CharField(max_length=20)),
                ('loanprovider', models.CharField(max_length=30)),
                ('loanamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loanduration', models.DurationField()),
                ('loanintr', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=264)),
                ('loan1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='loan_app.LoanInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
